variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - CASBACnetStack
  - build

Build BACnet Stack:  
  stage: CASBACnetStack
  tags:
    - windows
    - msvs
  before_script:
    - "echo #define CI_PIPELINE_IID %CI_PIPELINE_IID% >submodules/cas-bacnet-stack/source/CIBuildSettings.h"
    - "echo #define ENABLE_ALL_BIBBS >>submodules/cas-bacnet-stack/source/CIBuildSettings.h"    
    - "echo #define ENABLE_ALL_OBJECT_TYPES >>submodules/cas-bacnet-stack/source/CIBuildSettings.h"    
    - "cat submodules/cas-bacnet-stack/source/CIBuildSettings.h"    
  script:
    - "cd submodules/cas-bacnet-stack/"
    - "call build.cmd ReleaseLib Win32 CASBACnetStack"
    - "copy submodules/cas-bacnet-stack/bin/CASBACnetStack_Win32_Release.lib"

Windows Win32 Release:
  stage: build
  tags:
    - windows
    - msvs
  before_script:
    # Add MSBuild.exe to path
    - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
    # Update the CIBuildVersion.cs
    - cd BACnetServerExample
    - "echo const int CIBUILDNUMBER = %CI_PIPELINE_IID%; > CIBuildVersion.h"
    - type CIBuildVersion.h
    - cd ..
  script:
    # Create the bin directory if it does not exist
    - cd BACnetServerExample
    # Build and package the project in an apk for android
    - msbuild /p:Configuration=Release /p:Platform="x86"
    - cd ..\bin
    - dir
  artifacts:
    paths:
      - bin\BACnetServerExample_Win32_Release.exe
  